// app/(tabs)/profile/constants/mockData.ts
import { ProfileData, Ticket, Event, SavedEvent } from "./types";

export const profileData: ProfileData = {
  name: "Yodahe Ketema",
  // image: require("../../../../assets/dummy/kazaProfile.png"),
  stats: {
    // followers: 154,
    following: 26,
    // events: 6,
    // posts: 14,
  },
};

export const tickets: Ticket[] = [
  {
    id: "1",
    eventId: "E1",
    type: "Standard",
    name: ["You", " Abel", "Yodahe"],
    date: "Feb 10",
    time: "8:00 PM",
    avatars: [
      require("../../../../assets/dummy/eventMock.png"),
      require("../../../../assets/dummy/profileKaza.png"),
      require("../../../../assets/dummy/eventMock.png"),
    ],
    eventName: "Yidnekachew Concert",
    price: "800 ETB",
    place: "Millennium Hall, Addis Ababa",
    idNumber: "T-001234",
  },
  {
    id: "2",
    eventId: "E2",
    type: "VVIP",
    name: ["You", " Abel"],
    date: "Feb 10",
    time: "8:00 PM",
    avatars: [
      require("../../../../assets/dummy/kazaProfile.png"),
      require("../../../../assets/dummy/eventMock.png"),
    ],
    eventName: "Yidnekachew Concert",
    price: "600 ETB",
    place: "Millennium Hall, Addis Ababa",
    idNumber: "T-001235",
  },
  {
    id: "3",
    eventId: "E3",
    type: "Premium",
    name: ["You", " Abel"],
    date: "Feb 10",
    time: "8:00 PM",
    avatars: [
      require("../../../../assets/dummy/kazaProfile.png"),
      require("../../../../assets/dummy/eventMock.png"),
    ],
    eventName: "Yidnekachew Concert",
    price: "600 ETB",
    place: "Millennium Hall, Addis Ababa",
    idNumber: "T-001235",
  },
  {
    id: "4",
    eventId: "E4",
    type: "VIP",
    name: ["You", " Abel", "Beki", "Burak", "Yodahe"],
    date: "Feb 10",
    time: "8:00 PM",
    avatars: [
      require("../../../../assets/dummy/kazaProfile.png"),
      require("../../../../assets/dummy/eventMock.png"),
      require("../../../../assets/dummy/kazaProfile.png"),
      require("../../../../assets/dummy/eventMock.png"),
      require("../../../../assets/dummy/kazaProfile.png"),
    ],
    eventName: "Yidnekachew Concert",
    price: "600 ETB",
    place: "Millennium Hall, Addis Ababa",
    idNumber: "T-001235",
  },
  {
    id: "5",
    eventId: "E5",
    type: "Student",
    name: ["You", " Abel", "Beki", "Burak"],
    date: "Feb 10",
    time: "8:00 PM",
    avatars: [
      require("../../../../assets/dummy/kazaProfile.png"),
      require("../../../../assets/dummy/eventMock.png"),
      require("../../../../assets/dummy/kazaProfile.png"),
      require("../../../../assets/dummy/eventMock.png"),
    ],
    eventName: "Yidnekachew Concert",
    price: "600 ETB",
    place: "Millennium Hall, Addis Ababa",
    idNumber: "T-001235",
  },
];

export const events: Event[] = [
  {
    id: "1",
    title: "Jazz Night",
    organizer: "Bihromeda Events",
    date: "Jun 24, 2024",
    time: "7:00 PM",
    type: "Music",
    idNumber: "E001",
    place: "Jazz Club, Addis Ababa",
    venue: "Jazz Club",
    price: "300 ETB",
    image: require("../../../../assets/dummy/eventMock.png"),
    avatars: [
      require("../../../../assets/dummy/profileKaza.png"),
      require("../../../../assets/dummy/profileKaza.png"),
      require("../../../../assets/dummy/profileKaza.png"),
    ],
    count: 3,
    action: "Follow",
    review: "I enjoyed this event...",
    rating: 4,
    attendees: "400 went",
    reviewedBy: "200",
  },
  {
    id: "2",
    title: "Tech Conference 2024",
    organizer: "Innovators Hub",
    date: "Aug 15, 2024",
    time: "9:00 AM",
    type: "Conference",
    idNumber: "E002",
    place: "Innovation Hub, Addis Ababa",
    venue: "Innovation Hub",
    price: "500 ETB",
    image: require("../../../../assets/dummy/eventMock.png"),
    avatars: [
      require("../../../../assets/dummy/profileKaza.png"),
      require("../../../../assets/dummy/profileKaza.png"),
    ],
    count: 2,
    action: "Register",
    review: "Very informative and engaging.",
    rating: 5,
    attendees: "1200 went",
    reviewedBy: "746",
  },
  {
    id: "3",
    title: "Art Expo",
    organizer: "Creative Minds",
    date: "Sep 10, 2024",
    time: "10:00 AM",
    type: "Exhibition",
    idNumber: "E003",
    place: "Art Center, Addis Ababa",
    venue: "Art Center",
    price: "400 ETB",
    image: require("../../../../assets/dummy/eventMock.png"),
    avatars: [
      require("../../../../assets/dummy/profileKaza.png"),
      require("../../../../assets/dummy/profileKaza.png"),
    ],
    count: 2,
    action: "Follow",
    review: "Amazing artwork and great atmosphere.",
    rating: 4.5,
    attendees: "800 went",
    reviewedBy: "540",
  },
  {
    id: "4",
    title: "Food Festival",
    organizer: "Taste Ethiopia",
    date: "Oct 5, 2024",
    time: "12:00 PM",
    type: "Festival",
    idNumber: "E004",
    place: "Meskel Square, Addis Ababa",
    venue: "Meskel Square",
    price: "800 ETB",
    image: require("../../../../assets/dummy/eventMock.png"),
    avatars: [require("../../../../assets/dummy/profileKaza.png")],
    count: 1,
    action: "Join",
    review: "Delicious food and great variety.",
    rating: 4.8,
    attendees: "1500 went",
    reviewedBy: "979",
  },
  {
    id: "5",
    title: "Marathon 2024",
    organizer: "Run for Health",
    date: "Nov 20, 2024",
    time: "6:00 AM",
    type: "Sport",
    idNumber: "E005",
    place: "Stadium, Addis Ababa",
    venue: "National Stadium",
    price: "200 ETB",
    image: require("../../../../assets/dummy/eventMock.png"),
    avatars: [
      require("../../../../assets/dummy/profileKaza.png"),
      require("../../../../assets/dummy/kazaProfile.png"),
    ],
    count: 2,
    action: "Participate",
    review: "Well-organized and fun experience.",
    rating: 4.7,
    attendees: "2000 went",
    reviewedBy: "1223",
  },
];
export const savedEvents: SavedEvent[] = [
  {
    id: "1",
    eventId: "E1",
    title: "Yidnekachew Tebeje Music Tour",
    organizer: "Kaza Events",
    date: "Jun 24, 2024",
    eventDate: "Jun 24, 2024",
    eventTime: "8:00 PM",
    eventPlace: "Millennium Hall, Addis Ababa",
    eventPrice: "600 ETB",
    eventType: "Concert",
    action: "Saved",
    review: "Looking forward to this amazing concert!",
    rating: 5,
    attendees: "23k",
    description:
      "Kaza Events proudly presents Yidnekachew's new album tour featuring his latest hits.",
    hashtags: "#Yidne #TizitaBelbe #music",
    likesCount: "23k",
    commentsCount: "2k",
    image: require("../../../../assets/dummy/eventMock.png"),
    organiserImage: require("../../../../assets/dummy/profileKaza.png"),
    coverImage: require("../../../../assets/dummy/kazaProfile.png"),
  },
  {
    id: "2",
    eventId: "E2",
    title: "Sip and Paint Night",
    organizer: "Alis Bar",
    date: "Sep 20, 2024",
    eventDate: "Sep 20, 2024",
    eventTime: "6:30 PM",
    eventPlace: "Alis Bar, Bole",
    eventPrice: "350 ETB",
    eventType: "Art Workshop",
    action: "Saved",
    review: "Perfect combination of art and wine",
    rating: 4.5,
    attendees: "1.2k ",
    description:
      "Come join us as we explore the combination of art and wine in a relaxed atmosphere.",
    hashtags: "#paint #art #people",
    likesCount: "5k",
    commentsCount: "800",
    image: require("../../../../assets/dummy/eventMock.png"),
    organiserImage: require("../../../../assets/dummy/profileKaza.png"),
    coverImage: require("../../../../assets/dummy/kazaProfile.png"),
  },
];
export default {};
